/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // poldevSidebar: [{type: 'autogenerated', dirName: '.'}],
  polinfoSidebar: [

    { type: 'autogenerated', dirName: '.' },
  
  ],

/*
  // But you can create a sidebar manually
  polinfoSidebar: [

    // intro
    {
      type: 'doc',
      id: 'index',
      label: 'Introduction',
    },

    // infra
    {
      type: 'category',
      collapsed: false,
      label: 'Politique d\'infrastructure',
      link: {type: 'doc', id: 'infrastructure/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: '01_infrastructure/01_iaas',
        },
        {
          type: 'autogenerated',
          dirName: '01_infrastructure/02_paas',
        },
      ]
    },

    // support
    {
      type: 'category',
      label: 'Politique d\'informatique support',
      link: {type: 'doc', id: 'support/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: '02_support',
        },
      ]
    },

    // dev
    {
      type: 'category',
      label: 'Politique de développement',
      link: {type: 'doc', id: 'developpement/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: '03_developpement',
        },
      ]
    },


    // labo
    {
      type: 'category',
      label: 'Politique du labo',
      link: {type: 'doc', id: 'labo/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: '04_labo',
        },
      ]
    },

    // gouvernance
    {
      type: 'category',
      label: 'Gouvernance',
      link: {type: 'doc', id: 'gouvernance/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: '05_gouvernance',
        },
      ]
    },


  ],

*/

};

export default sidebars;
